object BuildPluginsVersion {
    const val DETEKT = "1.17.0"
    const val KTLINT = "10.1.0"
    const val FIREBASE_GMS = "4.3.10"
    const val ONESIGNAL = "0.13.4"
}

object Versions {
    const val KOTLIN = "1.6.10"
    const val APP_COMPAT = "1.4.1"
    const val MATERIAL = "1.5.0"
    const val RECYCLER_VIEW = "1.2.1"
    const val CONSTRAINT_LAYOUT = "2.1.3"
    const val CORE_KTX = "1.7.0"
    const val CORE = "2.1.0"
    const val LIFECYCLE = "2.4.0"
    const val DAGGER_HILT = "2.38.1"
    const val DAGGER_HILT_WORK = "1.0.0"
    const val COROUTINES = "1.5.1"
    const val FIREBASE_COROUTINES = "1.3.9"
    const val FIREBASE_STORAGE = "20.0.1"
    const val FIREBASE_FIRESTORE = "24.0.2"
    const val FIRECOIL = "1.3.0"
    const val ROBOLECTRIC = "4.5"
    const val RETROFIT = "2.9.0"
    const val REFLECT = "1.6.10"
    const val ONESIGNAL = "[4.0.0, 4.99.99]"
    const val OKHTTP = "4.9.1"
    const val MOSHI = "1.12.0"
    const val LEAK_CANARY = "2.7"
    const val NAVIGATION = "2.4.0"
    const val SWIPE_REFRESH = "1.1.0"
    const val TOASTER = "2.3.0"
    const val LOTTIE = "3.7.0"
    const val COIL = "1.2.2"
    const val IMAGE_CROPPER = "3.1.1"
    const val FIREBASE_AUTH = "19.2.0"
    const val FIREBASE_AUTH_KTX = "21.0.1"
    const val FIREBASE_GMS = "19.2.0"

    // Testing
    const val JUNIT = "4.13.2"
    const val RUNNER = "1.4.0"
    const val JUNIT_EXT = "1.1.3"
    const val ANDROIDX_ESPRESSO = "3.4.0"
    const val ANDROIDX_DAGGER_HILT = "1.0.0-alpha03"
    const val MOCKK = "1.12.2"
    const val FRAGMENT = "1.4.1"
    const val BARISTA = "3.9.0"
    const val KLUENT = "1.61"
    const val GOOGLE_TRUTH = "1.1.3"
    const val TURBINE = "0.6.1"
    const val ROOM = "2.4.2"
    const val JETPACK_SECURITY = "1.1.0-alpha03"
    const val WORK_MANAGER = "2.7.1"
}